export * from './ComitePage';
export * from './ContactoPage';
export * from './FormatoPage';
export * from './HomePage';
export * from './ObjetivoPage';
export * from './PostersRegistradosPage';
export * from './PreguntasPage';
export * from './ProgramaPage';
export * from './SedePage';